wildfly/wildfly-cekit-modules

- jboss/container/wildfly/launch-config/launch-common/added/launch/openshift-common.sh
- jboss/container/wildfly/launch/json-logging/added/launch/json_logging.sh
- jboss/container/wildfly/launch/json-logging/configure.sh
Summary
- Do not modify the config if the mode is "cli"
- Do not modify the config logging subsystem is not present
- Use cp -p when copy
@jfdenise these are the changes discussed this morning
> Fix behaviour for logging scripts

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
- jboss/container/wildfly/launch/jgroups/added/launch/ha.sh
- Additional fixes for ha.sh in jgroups
- Removes trailing new line from final generated CLI file to ensure we do not start embedded server if the file is empty
- prints error file in case of CLI errors were found
>  Additional fixes for JGroups and exec cli function

- jboss/container/wildfly/s2i/bash/configure.sh
Adding local galleon maven repo to user settings.xml @bstansberry @luck3y  that is the way the user will benefit from already downloaded artifacts without having an impact on incremental build.
The visible effect is that this repository is tried first to retrieve artifacts even for artifacts not already downloaded.
> Extends user settings with galleon local maven cache. 

- jboss/container/wildfly/launch/logger-category/added/launch/configure_logger_category.sh
- jboss/container/wildfly/launch/logger-category/tests/configure-logging-category.bats
- Enables the use of LOGGER_CATEGORIES env variable to work with CLI scripts.
- Fix logger categories bats tests
> Configure logger categories using CLI scripts

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
Needed when replacing WildFly with localy built one.
> call offliner from tmp dir to allow for error.logs to be written

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
@yersan @jfdenise I found when doing behave testing that the stuff we do in CLI to e.g. check for resources, print a warning and then exit does not actually print the warning. Also, the container continues to boot after the CLI error. Some background information here https://wildfly.zulipchat.com/#narrow/stream/194727-cloud/topic/CEKit.20testing/near/171514992
It does print the warning if CLI_DEBUG=true, but even then it only shows up in standard black/white.
Example usage from my WIP in datasource-common.sh:
```
local no_ds_subsystem_message_and_exit
local clashing_name_message_and_exit
generateCliValidationErrorAndExit "You have set environment variables to configure the datasource '${pool_name}'. Fix your configuration to contain a datasources subsystem for this to happen." …
```
> Cli validation

- jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh
- jboss/container/wildfly/launch/datasources/added/launch/datasource.sh
- jboss/container/wildfly/launch/datasources/added/launch/tx-datasource.sh
A later iteration will also fail fast if the list of added datasources does not contain ones asked for in:
-DEFAULT_JOB_REPOSITORY
-TIMER_SERVICE_DATA_STORE
-EE_DEFAULT_DATASOURCE
Tests are in https://github.com/wildfly/temp-eap-modules/pull/40
> Fail-fast in the datasources subsystem

- jboss/container/wildfly/launch/admin/added/launch/admin.sh
- jboss/container/wildfly/launch/mp-config/added/launch/mp-config.sh
admin.sh: Although security-realm is ignored when http-factory is set, it is cleaner to not set it.
mp-config.sh: Modified error message
> Do not use legacy realm when elytron used

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
- jboss/container/wildfly/launch/access-log-valve/added/launch/access_log_valve.sh
- jboss/container/wildfly/launch/jgroups/added/launch/ha.sh
- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
- jboss/container/wildfly/launch/jgroups/added/launch/jgroups_common.sh
- jboss/container/wildfly/launch/jgroups/module.yaml
- jboss/container/wildfly/launch/jgroups/test/ha.bats
- jboss/container/wildfly/launch/jgroups/test/jgroups.bats
- jboss/container/wildfly/launch/jgroups/test/server-configs/standalone-openshift-jgroups.xml
- jboss/container/wildfly/launch/jgroups/test/server-configs/standalone-openshift-pbcast.NAKACK2.xml
- jboss/container/wildfly/launch/jgroups/test/server-configs/standalone-openshift-with-elytron.xml
Enable JGroups encryption via CLI operations. Behave and bats tets passing.
It requires: https://github.com/wildfly/temp-eap-modules/pull/42
> Enable JGroups encryption via CLI operations

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/install-common/install-common.sh
https://issues.jboss.org/browse/WFWIP-214
- For pure cli execution, the driver content is not appended and script is executed
- For xml_cli, the driver content is appended and script execution is delayed at launch time.
An alternative of calling multiple time configure_drivers is by adding multiple prefixes to the DRIVERS env var.
This PR replaces: https://github.com/wildfly/wildfly-cekit-modules/pull/92
> Fix for WFWIP-214, append to CLI script file

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
By default, use 'echo' to get all the embedded server output which will be printed if an error is found here: https://github.com/yersan/wildfly-cekit-modules/blob/94ea07c886ce8e9dde4e152a9e19f19609eba650/jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh#L160
Jira issue: https://issues.jboss.org/browse/WFWIP-212
> [WFWIP-212] Always use echo for the embedded server output

- jboss/container/wildfly/galleon/provision-server/configure.sh
Deleting /tmp/hsperfdata_jboss created when using maven to provision server.
> Fix for WFWIP-221, jps can't see server process in Openshift

- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
- jboss/container/wildfly/launch/jgroups/test/jgroups.bats
These ops https://github.com/wildfly/wildfly-cekit-modules/blob/master/jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh#L152 should be equivalent to https://github.com/wildfly/wildfly-cekit-modules/blob/master/jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh#L100
Jira issue:https://issues.jboss.org/browse/WFWIP-226
> [WFWIP-226] Fix wrong properties for JGroups ASYM_ENCRYPT protocol

- jboss/container/wildfly/launch/messaging/added/launch/messaging.sh
In case of a warning message, for example, missing _SERVICE_HOST / _SERVICE_PROTOCOL, the embedded server tries to configure an empty default connection factory failing in that case.
> Fix empty default connection factory

- jboss/container/wildfly/launch/jgroups/added/launch/ha.sh
- jboss/container/wildfly/s2i/bash/module.yaml
- HA args are needed even when jgroups is not there.
- Upgrade to galleon 4.1.0 (that offers version convergence fix).
> Compute ha args when jgroups is not there, galleon upgrade

- jboss/container/wildfly/galleon/fp-content/base-layers/added/src/main/resources/layers/standalone/cloud-server/layer-spec.xml
- jboss/container/wildfly/galleon/fp-content/base-layers/added/src/main/resources/layers/standalone/datasources-web-server/layer-spec.xml
* Adjust for WF18, to merge only when WF 18 is released and WildFly s2i image is based on it.
> adjust base layers to WF 18

- jboss/container/wildfly/launch/tracing/module.yaml
Added documentation of missing additional environment variables that can be used to configure Tracing
They have been taken from https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core
> Add the list of Jaeger environment properties that can be used to configure Tracing

- jboss/container/wildfly/launch/keycloak/added/keycloak.sh
Issue: https://issues.jboss.org/browse/CLOUD-3430
> Fix for CLOUD-3430, CertificatePem not added to saml secured deployment

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
log_info expects just one argument which is the message to print in the standard output.
Jira issue: https://issues.jboss.org/browse/CLOUD-3441
> [CLOUD-3441] Duration of server configuration is not printed

- jboss/container/wildfly/galleon/fp-content/java/added/src/main/resources/packages/wildfly.s2i.java/content/bin/java-conf.conf
When java-default-options is sourced by any script to make use of its functions, by default prints to the standard output the calculated [JAVA_OPTS](https://github.com/jboss-openshift/cct_module/blob/master/jboss/container/java/jvm/bash/artifacts/opt/jboss/container/java/jvm/java-default-options#L172)
We cannot remove this echo, because it can be used by other parties to get the calculated values when sourcing it, so a workaround to avoid print this message when the server start could be to redirect to null the output when we are sourcing it in the standalone.conf file.
Jira issue: https://issues.jboss.org/browse/CLOUD-3440
> [CLOUD-3440] Redirect dynamic_resources.sh standard output to null when sourcing in standalone.conf

- jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-3448
@luck3y @kabir please, take a look
> [CLOUD-3448] typo fix: clearing the correct datasource environmental variables

- jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-3451
The default value for JTA attribute is true (based on the prior behaviour and the documentation)
> [CLOUD-3451] the default for JTA is true not false

- jboss/container/wildfly/galleon/fp-content/java/added/src/main/resources/packages/wildfly.s2i.java/content/bin/java-conf.conf
The solution is a bit hacky, but I haven't found a better approach, so maybe this one is acceptable.
EAP in standalone.sh will avoid adding any GC log file configuration if there is any JAVA_OPTS setting related to GC logs. This check clashes with the jvm_specific_diagnostics for JDK 11, where the -`Xlog:gc::utctime` decorator is enabled.
To prevent EAP skips the GC log file configuration due to the jvm_specific_diagnostics settings, we could remove the settings from the JAVA_OPTS and add them to PREPEND_JAVA_OPTS. That change will bypass the EAP specific checks.
jira issue: https://issues.redhat.com/browse/CLOUD-3188
> [CLOUD-3188] Move GC logs to PREPEND_JAVA_OPTS to bypass the specific EAP checks

- jboss/container/wildfly/launch/datasources/added/launch/tx-datasource.sh
https://issues.redhat.com/browse/CLOUD-3447
an adjustment of warning messages for tx mapping driver creation
follow-up to:  https://github.com/wildfly/wildfly-cekit-modules/pull/142
tests are here: https://github.com/jboss-container-images/jboss-eap-modules/pull/168
@kabir would you be so kind and review this?
> [CLOUD-3447] additional fix of warning message

- jboss/container/wildfly/launch-config/config/added/launch/launch.sh
Provide env var when starting server.
> Fix for Issue 155, ENV var set by launch scripts not conveyed to server.

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/install-common/install-common.sh
This PR follows up https://github.com/wildfly/wildfly-cekit-modules/pull/159 since it depends on it to avoid see an error when then the embedded server is used during S2I phase.
This patch allows overriding install-common.sh functions from wildfly-s2i by using /usr/local/s2i/install-common-overrides.sh
> [issue-147] Allows override install-common.sh functions from wildfly-s2i

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
Issue: https://issues.redhat.com/browse/CLOUD-3505 Fix for 0.18.x branch
The provisioned server is deleted from the target directory.
> Fix for CLOUD-3505, Provisioned server is not deleted once installed

- jboss/container/wildfly/galleon/fp-content/config/added/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
jpa-distributed is a new layer in WF19 beta3 that needs to be adjusted (jgroups and infinispan).
> Adapt jpa-distributed layer to openshift context

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
Issue: https://issues.redhat.com/browse/CLOUD-3516
In the build-artifacts image, in case a fat server has been provisioned (Galleon), JBOSS_HOME becomes a link to /s2i-output/server.
> Fix for CLOUD-3516, Avoid copying JBOSS_HOME content during s2i

- jboss/container/wildfly/launch/json-logging/added/launch/json_logging.sh
Jira issue: https://issues.redhat.com/browse/CLOUD-3554
Upstream Jira: https://issues.redhat.com/browse/CLOUD-3553
Upstream PR: https://github.com/wildfly/wildfly-cekit-modules/pull/173
> [CLOUD-3554] Add default handler formatter to default logging.properties when configuration is final

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
Issue: https://issues.redhat.com/browse/CLOUD-3516
In the build-artifacts image, in case a fat server has been provisioned (Galleon), JBOSS_HOME becomes a link to /s2i-output/server.
> [0.18.x] ]Fix for CLOUD-3516, Avoid copying JBOSS_HOME content during s2i

- jboss/container/wildfly/launch/json-logging/added/launch/json_logging.sh
When `CONFIG_IS_FINAL` environment variable is `true`, then placeholder replacements and CLI configurations are not performed meaning the user supply the final server configuration file.
In order to avoid supply the initial logging.properties file, this path replace and initialises a default console formatter for the existing logging.properties in the image.
Jira issue: https://issues.redhat.com/browse/CLOUD-3553
> [CLOUD-3553] Add default handler formatter to default logging.properties when configuration is final

- jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh
- jboss/container/wildfly/launch/datasources/test/datasource/common.bash
- jboss/container/wildfly/launch/datasources/test/datasource/configure.bats
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/default_bindings_placeholder.xml
There are two different placeholders to set the default data source:
1. `##DEFAULT_DATASOURCE##`
2. ``
The placeholder 1) was not replaced, which makes server fail at startup if the user this placeholder in his server config file.
Jira issue: https://issues.redhat.com/browse/CLOUD-3549
> [CLOUD-3549] Placeholder ##DEFAULT_DATASOURCE## is not replaced during the container startup process

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
Issue: https://issues.redhat.com/browse/CLOUD-3603
The processing of errors/warnings prior to start the server creates an empty warning file. this file should be deleted instead of emptying its content.
> Fix for CLOUD-3603, org.jboss.as.cli warning without message 

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
Issue: https://issues.redhat.com/browse/CLOUD-3607
> Fix for CLOUD-3607, Move Image Builder non maven repo content out of tmp

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
Fix for https://issues.redhat.com/browse/WFLY-13577
> Fix for WFLY-13577, Warning when deleting non existing CLI warning file

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/s2i/bash/module.yaml
Issue https://github.com/wildfly/wildfly-cekit-modules/issues/187
* Added script Hook.
* Upgraded wildfly galleon version to 4.2.7. Required for s2i Galleon feature-pack to express dependencies on Galleon patches.
> [0.18.x] Fix for Issue #187, Add ability to execute a script once the maven repository has been unzipped.

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/s2i/bash/module.yaml
Issue https://github.com/wildfly/wildfly-cekit-modules/issues/187
* Added script Hook.
* Upgraded wildfly galleon version to 4.2.7. Required for s2i Galleon feature-pack to express dependencies on Galleon patches.
> [Master] Fix for Issue #187, Add ability to execute a script once the maven repository has been unzipped.

- jboss/container/wildfly/launch/keycloak/added/keycloak.sh
Issue: https://issues.redhat.com/browse/JBEAP-19847
Upstream Issue: Not required
> JBEAP-19847 - bash syntax error occurs in keycloak.sh when CONFIG_IS_FINAL is enabled

- jboss/container/wildfly/launch/admin/added/launch/admin.sh
Issue: https://issues.redhat.com/browse/CLOUD-3768
* mode variable is not defined in the else case.
> Fix for CLOUD-3768, admin.sh doesn't define mode in else case

- jboss/container/wildfly/launch/admin/added/launch/admin.sh
Fix for 0.18.x branch.
Issue: https://issues.redhat.com/browse/CLOUD-3768
* mode variable is not defined in the else case.
> [0.18.x] Fix for CLOUD-3768, admin.sh doesn't define mode in else case

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
Issues: https://issues.redhat.com/browse/CLOUD-3607 and https://issues.redhat.com/browse/CLOUD-3769
> [0.18.x] Fix for CLOUD-3607, Move Image Builder non maven repo content out of tmp

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
Issue: https://issues.redhat.com/browse/CLOUD-3769
> Fix for CLOUD-3769, Unzipped repo misc content should be moved out of tmp dir only if it exists

- jboss/container/wildfly/galleon/fp-content/config/added/src/main/resources/feature_groups/os-infinispan.xml
> Fix for Issue #198, replicated-cache.memory.object has been renamed replicated-cache.memory.heap

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
https://issues.redhat.com/browse/CLOUD-3855
> [CLOUD-3855] - chown shouldn't fail if the jboss user doesn't exist

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
https://issues.redhat.com/browse/CLOUD-3855
> [CLOUD-3855] chown shouldn't fail if the jboss user doesn't exist

- jboss/container/wildfly/galleon/fp-content/config/added/src/main/resources/layers/standalone/ejb-dist-cache/layer-spec.xml
Adds OpenShift adjustments for `ejb-dist-cache` Galleon layer
Jira issue: https://issues.redhat.com/browse/CLOUD-3470
> [CLOUD-3470] Add JGroups adjustments for ejb-dist-cache Galleon layer

- jboss/container/wildfly/launch/datasources/added/launch/datasource.sh
Reverts wildfly/wildfly-cekit-modules#213
Reverting this as it appears to cause regressions in testing. Will comment on the JIRA
> Revert "[CLOUD-3649] configure drivers from env variables prior datasource co…"

- jboss/container/wildfly/launch-config/config/added/launch/launch.sh
Issue: https://issues.redhat.com/browse/CLOUD-3953
> Fix for CLOUD-3953, Arguments not conveyed to server if restarted after extensions applied

- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
Issue: https://issues.redhat.com/browse/JBEAP-20733
Upstream Issue: https://issues.redhat.com/browse/CLOUD-3509
Upstream PR: https://github.com/wildfly/wildfly-cekit-modules/pull/164
> CLOUD-3509 correct misspelling of keystore

- jboss/container/wildfly/galleon/fp-content/java/added/src/main/resources/packages/wildfly.s2i.java/content/bin/java-conf.conf
Remove the Max value. This change is not enough.
In addition:
* cct_module needs to be fixed to not set a default max value: https://github.com/jboss-openshift/cct_module/pull/396
* Each image needs to provision a standalone.conf file that doesn't set the Max value: https://github.com/wildfly/wildfly-s2i/pull/152
> [CLOUD-3964] Remove default value for max metaspace

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/galleon/provision-server/configure.sh
Maven 3.5 got EOL'd. Bump it to v3.6
Signed-off-by: Daniel Kreling <dkreling@redhat.com>
> [CLOUD-3951] Bump maven module version to 3.6

- jboss/container/wildfly/galleon/fp-content/config/added/src/main/resources/feature_groups/os-clustering.xml
Resolves
https://issues.redhat.com/browse/CLOUD-3979
https://issues.redhat.com/browse/CLOUD-3980
> CLOUD-3979 The distributable-web subsystem needs to use <infinispan-routing cache-container="web" cache="routing"/>, instead of <local-routing/>.

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/galleon/build-feature-pack/module.yaml
- jboss/container/wildfly/launch/elytron/configure.sh
- jboss/container/wildfly/s2i/bash/module.yaml
These changes are needed in order to add more flexiility in the way cekit modules can be used to construct an image.
* Upgrade to 5.2.0.Alpha2 contains a fix that has been revealed when building a FP that depends on more than one FP.
* The elytron/configure.sh script was sourcing a file for no reason.
* GALLEON_FP_COMMON_PKG_NAME env that used to be mandatory in order to copy content from JBOSS_HOME to the s2i FP is no more mandatory.
These changes are needed by: https://github.com/wildfly/wildfly-s2i/pull/173
> Upgrade to galleon-plugins 5.2.0.Alpha2. Fixed elytron/configure.sh. GALLEON_FP_COMMON_PKG_NAME env is no more mandatory

- jboss/container/wildfly/run/api/module.yaml
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run
* Introduce the ability to run a CLI script at startup. Run script and API updated.
* Ability to set CLI output location (by default in a file but can be displayed in the console).
* New behave tests will be added in a wildfly-s2i PR.
> [V2] Support execution of a CLI script at runtime

- jboss/container/wildfly/galleon/fp-content/config/added/src/main/resources/feature_groups/os-infinispan-web-repl-cache.xml
- jboss/container/wildfly/galleon/fp-content/config/added/src/main/resources/feature_groups/os-infinispan.xml
* Fix replicated caches added to server configuration. Caused by https://issues.redhat.com/browse/WFLY-14935
> Set default expiration value to 0 for infinispan replicated caches

- jboss/container/wildfly/launch/datasources/added/launch/tx-datasource.sh
https://issues.redhat.com/browse/CLOUD-4021
https://issues.redhat.com/browse/EAPSUP-592
expecting to be backported to `0.18.x` branch later
/cc @luck3y
> [CLOUD-4021] dot is not permitted in tx datasource table name

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
- jboss/container/wildfly/s2i/bash/artifacts/usr/local/s2i/usage
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/generic_layers/config.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/generic_layers/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i-core-hooks
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/install-common/install-common.sh
- jboss/container/wildfly/s2i/legacy/configure.sh
- jboss/container/wildfly/s2i/legacy/module.yaml
* A cekit module that captures legacy s2i workflow (galleon provisioning, copy of content into server, calling extensions).
* Clean-up s2i cekit module from WildFly specific setup, allow to be shared with other technologies.
> Introduce legacy s2i module to enable current s2i workflow

- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/default_config/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/generic_layers/config.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/generic_layers/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/generic_provisioning/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
- jboss/container/wildfly/s2i/legacy/module.yaml
* Replace usage of galleon maven plugin by the usage of WildFly Maven plugin for legacy provisioning.
* Allow for multiple feature-packs when generating the default configuration. the latest FP being used to provide default configuration(s).
> Fix for Issue #277, Provisioning based on env variables should use WildFly maven plugin

- jboss/container/wildfly/launch/elytron/added/launch/elytron.sh
- jboss/container/wildfly/launch/elytron/test/elytron.bats
- jboss/container/wildfly/launch/elytron/test/security-domains.bats
- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
- jboss/container/wildfly/launch/jgroups/test/jgroups.bats
* Allow for HTTPS_KEYSTORE_TYPE to be not set. Do not set a type, let elytron handle the keystore type.
* Added new unit tests
* Changed warning message.
* JCEKS is still the default for JGroups encryption.
> Fix for Issue #279, Keystore type shouldn't be mandatory when generating HTTPS configuration using elytron

- jboss/container/wildfly/launch/keycloak/added/keycloak.sh
See: https://issues.redhat.com/browse/RHPAM-3888
> [RHPAM-3888] SSO integration fails for multiple Realm certificates

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/disabled-copy-hooks
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/maven-s2i-overrides
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
* Detect special case of a directory being a server directory. Disable any copy of custom content, there are no, just a server.
> Fix for WFWIP-432, Improve binary build experience for server mode

- jboss/container/wildfly/run/api/module.yaml
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run-utils.sh
- jboss/container/wildfly/run/bash/test/run.bats
* run entrypoint to add the export. Can be disabled thanks to an env variable.
* Refactored run entry points to allow to test some functions.
* Added bats tests for run entrypoint
* Re-ordered API documentation.
> Fix for Issue #320, [JDK17] Missing modular export when enabling dns ping protocol

- jboss/container/wildfly/galleon/cloud-galleon-pack/java/added/src/main/resources/packages/wildfly.s2i.java/content/bin/java-conf.conf
standalone.conf adapts to execution context.
> Fix for Issue #322, if dynamic_resources.sh isn't available the server should still be able to start.

- jboss/container/wildfly/launch/access-log-valve/added/launch/access_log_valve.sh
- jboss/container/wildfly/launch/deployment-scanner/added/launch/deploymentScanner.sh
- jboss/container/wildfly/launch/json-logging/added/launch/json_logging.sh
- jboss/container/wildfly/launch/keycloak/2.0/added/keycloak.sh
- jboss/container/wildfly/launch/messaging/2.0/added/launch/messaging.sh
- jboss/container/wildfly/launch/mp-config/added/launch/mp-config.sh
- jboss/container/wildfly/launch/oidc/added/oidc.sh
- jboss/container/wildfly/launch/tracing/added/launch/tracing.sh
Update launch scripts that can be configured from ENV_FILES. 
This PR will be NOT opened against 0.23.x branch, only applied to WF26+. 
We stay on the safe side and only fix in 0.23.x reported bugs.
> Fix for Issue #335, add support for ENV_FILES for launch scripts that can support it

- jboss/container/wildfly/run/bash/module.yaml
This activates the ability to override management attribute values using
environment variables as described in
https://github.com/wildfly/wildfly-proposals/blob/main/management/WFCORE-5489_override_attribute_value_from_env_var.adoc.
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>
> Set WILDFLY_OVERRIDING_ENV_VARS env var

- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
- jboss/container/wildfly/launch/jgroups/module.yaml
- jboss/container/wildfly/launch/jgroups/test/ha.bats
- jboss/container/wildfly/launch/jgroups/test/jgroups.bats
Removing checks of JGROUPS_ENCRYPT_SECRET, this env variable is actually no more in context (using helm Charts, no more template).
> Fix for #346, JGROUPS_ENCRYPT_SECRET is now useless

- jboss/container/wildfly/galleon/cloud-galleon-pack/finalize-script/added/src/main/resources/resources/wildfly/scripts/finalize.cli
For both FD_SOCK and FD_SOCK2, unset the socket binding attribute prior to socket-binding removal.
> Fix for #348, Unset socket-binding attribute for FD_SOCK protocol, required for 27 Beta1

- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/base/added/src/main/resources/feature_groups/os-socket.xml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/base/added/src/main/resources/feature_groups/os-undertow.xml
- jboss/container/wildfly/run/api/module.yaml
Introduce a bindall interface, make http/https socket-binding to depend on it.
This change impacts all galleon layers provisioned with the wildfly-cloud-galleon-pack.
> Fix for Issue #350, http and https listener should be bound to 0.0.0.0

- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/feature_groups/os-jgroups.xml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/layers/standalone/ejb-dist-cache/layer-spec.xml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/layers/standalone/web-clustering/layer-spec.xml
The side effect of un-setting an attribute of a non existing resource (FD_SOCK protocol has been removed), is to add the protocol FD_SOCK resource.
> Fix for Issue #358, FD_SOCK protocol is added to the server configuration

- .github/workflows/test-wildfly-s2i.yml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/feature_groups/os-clustering.xml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/layers/standalone/ejb-dist-cache/layer-spec.xml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/layers/standalone/jpa-distributed/layer-spec.xml
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/clustering/added/src/main/resources/layers/standalone/web-clustering/layer-spec.xml
These excludes are left over from https://github.com/wildfly/wildfly-cekit-modules/pull/362.
Could have a side effect when provisioning cloud FP alone.
> Remove code to exclude ha sockets

- jboss/container/wildfly/s2i/2.0/legacy/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
* Remove the deprecation warning when the S2I env vars `GALLEON_PROVISION_FEATURE_PACKS` or `GALLEON_USE_LOCAL_FILE` are used
* Change the warning log to an info log as this is a valid use case to use these env vars to create an application image without access to the source code of the Jakarta EE application
JIRA: https://issues.redhat.com/browse/JBEAP-25347
> [JBEAP-25347] Remove deprecation warning for S2I provisioning env vars

- jboss/container/wildfly/s2i/2.0/legacy/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
* Remove the deprecation warning when the S2I env vars `GALLEON_PROVISION_FEATURE_PACKS` or `GALLEON_USE_LOCAL_FILE` are used
* Change the warning log to an info log as this is a valid use case to use these env vars to create an application image without access to the source code of the Jakarta EE application
JIRA: https://issues.redhat.com/browse/JBEAP-25347
> [0.29.alpha1.x] [JBEAP-25347] Remove deprecation warning for S2I provisioning env vars

- jboss/container/wildfly/launch/keycloak/2.0/added/keycloak.sh
Keycloak SAML feature-pack 22.0.1 has a module renaming that breaks the feature.
> Fix for Issue #387, keycloak SAML automatic registration uses wrong JBoss Modules module name

- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/base/added/src/main/resources/feature_groups/os-undertow.xml
Resolves
https://issues.redhat.com/browse/CLOUD-4174
> CLOUD-4174 Session affinity information is attached to the session ID but never used
