wildfly/wildfly-cekit-modules

- jboss/container/wildfly/launch-config/config/added/launch/configure-main.sh
- jboss/container/wildfly/launch-config/launch-common/added/launch/openshift-common.sh
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/install-common/install-common.sh
- jboss/container/wildfly/s2i/bash/configure.sh
- jboss/container/wildfly/s2i/bash/module.yaml
Summary:
- Add common scripts shared between project and product
- Add the required changes to enable Drivers via CLI
> Added common scripts for S2I to enable Drivers

- jboss/container/wildfly/launch/tracing/added/launch/tracing.sh
- jboss/container/wildfly/launch/tracing/configure.sh
removed call to files.sh that is useless in configure.sh
> tracing.sh fix and remove subsystem only if env var is false

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/galleon/build-feature-pack/module.yaml
- jboss/container/wildfly/galleon/provision-server/configure.sh
- jboss/container/wildfly/galleon/provision-server/module.yaml
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/run.sh
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/s2i-core-hooks
- jboss/container/wildfly/s2i/bash/configure.sh
- jboss/container/wildfly/s2i/bash/module.yaml
- provision server
- build FP
- s2i integration.
> galleon cekit modules

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
- jboss/container/wildfly/launch/jgroups/added/launch/ha.sh
Fix some problems found in jgroups ha.sh and activate the CLI_DEBUG if we are already using SCRIPT_DEBUG
>  Fix some problems with jgroups script and enable CLI_DEBUG with SCRIPT_DEBUG

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
- jboss/container/wildfly/launch/mp-config/added/launch/mp-config.sh
- Check CONFIG_IS_FINAL if it is defined before use it
- Micro profile config, CLI should fail if the Microprofile config is already configured
> Additional checks before adding Micro Profile config via CLI

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/galleon/provision-server/configure.sh
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/save-artifacts.sh
- jboss/container/wildfly/s2i/bash/module.yaml
- Separate provisioning cache from app cache
- Delegate app cache incremental handling to maven-s2i module
- Implement diff to identofy custom provisioning artifacts and store them.
- Sync provisioning cache with provisioning artifacts from previous build during assemble.
> Incremental for galleon artifacts

- jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh
- jboss/container/wildfly/launch/datasources/test/datasource.bats
- jboss/container/wildfly/launch/datasources/test/datasource/configure.bats
I need to update the document to reflect these changes
> Pull in legacy repo 7.2.x-openjdk11/os-eap-datasource/1.0 changes

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
- jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh
- jboss/container/wildfly/launch/datasources/added/launch/datasource.sh
- jboss/container/wildfly/launch/datasources/test/datasource/configure.bats
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_mysql_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_other_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_other_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_postgresql_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_postgresql_nourl_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_sybase_validation_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/no-datasource-enabled-default.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/no-datasource-no-default.xml
I think this contains everything touched by the datasources scripts.
Contains https://github.com/wildfly/wildfly-cekit-modules/pull/15 which moves to 'no drivers'
> Other datasource subsystems and no drivers

- jboss/container/wildfly/launch/https/added/https.sh
- jboss/container/wildfly/launch/https/configure.sh
- jboss/container/wildfly/launch/https/module.yaml
Added https script to configure via CLI/Markers the legacy https configuration
> Enable legacy https configuration via CLI scripts

- jboss/container/wildfly/launch/https/module.yaml
> Add https module doc

- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/extend_config/pom.xml
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/pom.xml
- jboss/container/wildfly/s2i/bash/module.yaml
make galleon versions resolved from env var. 
Fix optional-packages for config extension
> make galleon versions resolved from env var. 

- jboss/container/wildfly/launch/security-domains/module.yaml
Adding missing module description
> Add missing jboss.container.wildfly.launch.security-domains description

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
as well as after. The reason is that when generating the CLI scripts
we sometimes need to do XPath checks which are running in a
sub-shell. When running in a sub-shell echo/log_error/log_warning
are not guaranteed to be shown in the console, so in these places
they should redirect to the cli error/warn file
> Process errors and warnings before running the CLI script

- jboss/container/wildfly/launch/resource-adapters/added/launch/resource-adapter.sh
- jboss/container/wildfly/launch/resource-adapters/added/launch/resource-adapters-common.sh
- jboss/container/wildfly/launch/resource-adapters/configure.sh
- jboss/container/wildfly/launch/resource-adapters/module.yaml
This is a trio of PRs. The others are:
https://github.com/wildfly/temp-openshift-image/pull/18
https://github.com/wildfly/temp-eap-modules/pull/32
> Port resource-adapters, and set up CLI

- jboss/container/wildfly/galleon/provision-server/artifacts/settings-startup.xml
- jboss/container/wildfly/galleon/provision-server/configure.sh
- jboss/container/wildfly/galleon/provision-server/module.yaml
- jboss/container/wildfly/launch-config/os/added/launch/files.sh
- jboss/container/wildfly/launch-config/os/tests/files.bats
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
- jboss/container/wildfly/s2i/bash/configure.sh
- jboss/container/wildfly/s2i/bash/module.yaml
- jboss/container/wildfly/s2i/bash/tests/s2i_galleon.bats
* files.sh, retrieve jar files from maven local repo
* Dissociate settings.xml used at s2i provisioning, s2i app build and start-up.
* Added bats tests for files.sh and slim-server
> slim server

- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
- jboss/container/wildfly/launch/access-log-valve/added/launch/access_log_valve.sh
- jboss/container/wildfly/launch/access-log-valve/configure.sh
- jboss/container/wildfly/launch/access-log-valve/module.yaml
This is a trio of three pull requests. These are:
* https://github.com/wildfly/wildfly-cekit-modules/pull/48
* https://github.com/wildfly/temp-eap-modules/pull/34
* https://github.com/wildfly/temp-openshift-image/pull/21
> Access log valve

- jboss/container/wildfly/launch-config/config/added/launch/launch.sh
- jboss/container/wildfly/launch-config/config/added/launch/openshift-common.sh
- jboss/container/wildfly/launch-config/os/added/launch/configure-modules.sh
- jboss/container/wildfly/launch-config/os/added/launch/launch-common.sh
- jboss/container/wildfly/launch/extensions/added/configure_extensions.sh
- jboss/container/wildfly/launch/extensions/configure.sh
- jboss/container/wildfly/launch/extensions/module.yaml
- jboss/container/wildfly/launch/security-domains/added/launch/login-modules-common.sh
- jboss/container/wildfly/launch/security-domains/configure.sh
- jboss/container/wildfly/launch/security-domains/tests/login-modules.bats
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
- jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/s2i-core-hooks
* New extensions module
* Support for other login modules
* Refactored script for extension.
@yersan , this contains the refactoring required by extensions
> other login module support, refactor script for extensions, extensions module

- jboss/container/wildfly/launch/admin/added/launch/management-common.sh
- jboss/container/wildfly/launch/elytron/added/launch/elytron.sh
- jboss/container/wildfly/launch/elytron/module.yaml
- jboss/container/wildfly/launch/elytron/test/security-domains.bats
- jboss/container/wildfly/launch/resource-adapters/added/launch/resource-adapters-common.sh
- jboss/container/wildfly/launch/resource-adapters/module.yaml
In addition, added support for management-common.sh. This is an API exposed that needed CLI support.
> Elytron only for security domains and resource-adapters

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/galleon/fp-content/jolokia/added/src/main/resources/packages/wildfly.s2i.jolokia/content/bin/jolokia-conf.conf
* Detect if the zipped artifact is available, use it and skip offliner
* jolokia needed jars are now in other modules. Evolved standalone.conf.
> Support for zipped repo, adjust to jakarta changes

- jboss/container/wildfly/launch-config/os/added/launch/configure-modules.sh
- jboss/container/wildfly/launch/jgroups/added/launch/ha.sh
- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
- jboss/container/wildfly/launch/jgroups/added/launch/jgroups_common.sh
- jboss/container/wildfly/launch/jgroups/test/ha.bats
- jboss/container/wildfly/launch/jgroups/test/jgroups.bats
- jboss/container/wildfly/launch/jgroups/test/protocol_list.bats
- jboss/container/wildfly/launch/jgroups/test/server-configs/standalone-openshift-jgroups-protocol-store.xml
Enables the uses of files to shared information about the protocol list modified by ha.sh and jgroups.sh scripts.
> Use files to track the list of JGroups protocols

- jboss/container/wildfly/galleon/fp-content/ejb-tx-recovery/added/src/main/resources/packages/wildfly.s2i.ejb.tx.recovery/content/bin/launch/statefulset.sh
- jboss/container/wildfly/galleon/fp-content/ejb-tx-recovery/added/src/main/resources/packages/wildfly.s2i.ejb.tx.recovery/package.xml
- jboss/container/wildfly/galleon/fp-content/ejb-tx-recovery/configure.sh
- jboss/container/wildfly/galleon/fp-content/ejb-tx-recovery/module.yaml
Requires: 
https://github.com/wildfly/temp-eap-modules/pull/59
https://github.com/wildfly/temp-openshift-image/pull/35
> [EAP7-1353] Enable EJB client transaction recovery configuration

- jboss/container/wildfly/launch/elytron/test/security-domains.bats
- jboss/container/wildfly/launch/https/added/https.sh
- jboss/container/wildfly/launch/https/test/https.bats
- jboss/container/wildfly/launch/jgroups/test/ha.bats
- jboss/container/wildfly/launch/jgroups/test/jgroups.bats
- jboss/container/wildfly/launch/jgroups/test/protocol_list.bats
- jboss/container/wildfly/launch/logger-category/added/launch/configure_logger_category.sh
- jboss/container/wildfly/launch/logger-category/tests/configure-logging-category.bats
- jboss/container/wildfly/launch/messaging/test/messaging.bats
- jboss/container/wildfly/launch/security-domains/tests/login-modules.bats
- jboss/container/wildfly/launch/tracing/test/tracing.bats
- test-common/cli_utils.sh
- Additionally, extracted common tests CLI utilities to a file
> Add bats tests for CLI operations for legacy https and logger categories

- jboss/container/wildfly/launch/elytron/added/launch/elytron.sh
- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
- jboss/container/wildfly/launch/jgroups/module.yaml
- jboss/container/wildfly/launch/jgroups/test/jgroups.bats
- test-common/cli_utils.sh
Jira issue: https://issues.jboss.org/browse/WFWIP-229
> [WFWIP-229] Enable non-deprecated version of JGroups ASYM_ENCRYPT

- jboss/container/wildfly/launch/keycloak/added/keycloak.sh
Extend existing other application-security-domain that references ApplicationDomain with keycloak mechanisms. That only applies to elytron security.
Fix a finding, SSO_SECURITY_DOMAIN was not unset.
> Fix for WFWIP-257, SSO layer cannot be properly used with SSO template

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/galleon/provision-server/configure.sh
- jboss/container/wildfly/s2i/bash/configure.sh
- jboss/container/wildfly/s2i/bash/module.yaml
Issue: https://issues.jboss.org/browse/WFWIP-258
> Fix for WFWIP-258, Galleon Maven repo in builder image contains additional artifacts

- jboss/container/wildfly/s2i/bash/module.yaml
Issue: https://issues.jboss.org/browse/CLOUD-3445
> Fix for CLOUD-3445, Upgrade galleon version to 4.1.2.Final

- jboss/container/wildfly/galleon/fp-content/ejb-tx-recovery/module.yaml
- jboss/container/wildfly/launch/statefulset/added/launch/statefulset.sh
- jboss/container/wildfly/launch/statefulset/configure.sh
- jboss/container/wildfly/launch/statefulset/module.yaml
Introduce launch module for statefulset script.
> Fix for issue 151, Refactor statefulset support

- jboss/container/wildfly/launch-config/config/added/launch/launch.sh
Legacy server configuration based on CLI + embedded server.
> Expose function to configure server with CLI

- jboss/container/wildfly/launch/jgroups/added/launch/jgroups.sh
https://issues.redhat.com/browse/CLOUD-3509
> CLOUD-3509 correct typo of keystore

- jboss/container/wildfly/s2i/bash/module.yaml
Issue: https://issues.redhat.com/browse/CLOUD-3557
> Fix for CLOUD-3557, Upgrade galleon to 4.2.4

- .github/workflows/main.yml
- .gitignore
- jboss/container/wildfly/launch-config/os/added/launch/files.sh
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_ibmdb2_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_mysql_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_other_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_other_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_postgresql_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_postgresql_nourl_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_sybase_pool_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/datasources_sybase_validation_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/no-datasource-enabled-default.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/no-datasource-no-default.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/prefix_ibmdb2_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/prefix_mysql_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/prefix_mysql_xa_explicit_driver.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/prefix_oracle_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/prefix_postgresql_nonxa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/prefix_postgresql_xa.xml
- jboss/container/wildfly/launch/datasources/test/datasource/expectations/prefix_postgresql_xa_explicit_driver.xml
- jboss/container/wildfly/launch/keycloak/tests/bats/hostname-discovery.bats
- run-all-tests.sh
- test-common/default-env.sh
https://issues.redhat.com/browse/CLOUD-3626
> CLOUD-3626 - enable github actions for running bats tests

- jboss/container/wildfly/launch/keycloak/added/keycloak.sh
That's mostly for code quality and ease of reading.
> Standardize use of command substitution using the recommended syntax

- jboss/container/wildfly/s2i/bash/module.yaml
Issue: https://issues.redhat.com/browse/CLOUD-3858
> Fix for CLOUD-3858, Upgrade Galleon versions to align with EAP 7.3.4

- jboss/container/wildfly/galleon/build-feature-pack/module.yaml
- jboss/container/wildfly/galleon/fp-content/jolokia/module.yaml
- jboss/container/wildfly/galleon/provision-server/module.yaml
- jboss/container/wildfly/s2i/bash/module.yaml
> Update modules to match naming in cct_module v0.44.0

- jboss/container/wildfly/galleon/build-feature-pack/configure.sh
- jboss/container/wildfly/galleon/provision-server/configure.sh
https://issues.redhat.com/browse/CLOUD-3955
> [CLOUD-3951] Bump maven module version to 3.6

- .github/workflows/main.yml
Build and run WildFly s2i tests using wildfly-cekit-modules PR branch.
> Github action to build/test wildfly-s2i on PR

- .github/workflows/v2-push.yml
* Send event to wildfly-s2i repo on push in v2 branch.
> [V2] Action to deploy WildFly s2i images on push

- jboss/container/wildfly/launch/datasources/added/launch/tx-datasource.sh
https://issues.redhat.com/browse/CLOUD-4021
https://issues.redhat.com/browse/EAPSUP-592
master PR: #257
0.23.x PR: https://github.com/wildfly/wildfly-cekit-modules/pull/258
> [CLOUD-4021] dot is not permitted in tx datasource table name

- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/assemble.sh
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/default_config/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/generic_layers/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/generic_provisioning/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/provisioning/pom.xml
- jboss/container/wildfly/s2i/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
- jboss/container/wildfly/s2i/legacy/module.yaml
* Allow to provision default config
* Support for "local to project" provisioning.xml
> Legacy support

- jboss/container/wildfly/launch/keycloak/added/keycloak.sh
Signed-off-by: desmax74 <mdessi@redhat.com>
See:https://issues.redhat.com/browse/RHPAM-3888
@jfdenise
> [RHPAM-3888] 0.23.x SSO integration fails for multiple Realm certificates

- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/base/added/src/main/resources/layers/standalone/embedded-activemq/layer-spec.xml
> Fix for #340, embedded-activemq Galleon layer needs adjustment for openshift

- jboss/container/wildfly/run/api/module.yaml
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run-utils.sh
- jboss/container/wildfly/run/bash/test/run.bats
WF 27 Final will add it by default.
> Fix for Issue #354, Remove addition of JPMS argument jdk.naming.dns/com.sun.jndi.dns

- jboss/container/wildfly/s2i/bash/module.yaml
Issue: https://issues.redhat.com/browse/CLOUD-4152
This can be merged when https://github.com/jbossas/jboss-eap7/pull/4425 is merged.
> [0.23.x] Fix for CLOUD-4152, Upgrade to Galleon 4.2.9.Final

- .github/workflows/test-wildfly-cloud-fp.yml
- .github/workflows/test-wildfly-s2i.yml
- jboss/container/wildfly/launch/keycloak/2.0/added/keycloak.sh
- jboss/container/wildfly/launch/keycloak/2.0/module.yaml
> SAML support fixes

- .github/workflows/test-wildfly-s2i.yml
- jboss/container/wildfly/s2i/2.0/legacy/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon
- jboss/container/wildfly/s2i/2.0/legacy/module.yaml
- jboss/container/wildfly/s2i/2.0/legacy/test/channels.bats
Issue: https://issues.redhat.com/browse/WFWIP-556
> Fix for WFWIP-556, support for channel split into channel and manifest

- jboss/container/wildfly/launch-config/config/1.0/added/launch/launch.sh
- jboss/container/wildfly/launch-config/config/2.0/added/launch/launch.sh
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run-utils.sh
https://issues.redhat.com/browse/JBEAP-24811
> JBEAP-24811 Improve message for CLI_GRACEFUL_SHUTDOWN system property

- .github/workflows/main.yml
- .github/workflows/push-deploy-images.yml
- .github/workflows/test-wildfly-cloud-fp.yml
- .github/workflows/test-wildfly-s2i.yml
> Trivial stylization fixes around WildFly / CEKit projects.

- jboss/container/wildfly/galleon/cloud-galleon-pack/launch-openshift/added/src/main/resources/packages/wildfly.s2i.common/content/bin/openshift-launch.sh
- jboss/container/wildfly/galleon/cloud-galleon-pack/layers/base/added/src/main/resources/feature_groups/os-tx-recovery.xml
- jboss/container/wildfly/galleon/fp-content/ejb-tx-recovery/added/src/main/resources/packages/wildfly.s2i.ejb.tx.recovery/content/bin/launch/statefulset.sh
- jboss/container/wildfly/launch/jgroups/added/launch/ha.sh
- jboss/container/wildfly/launch/os/node-name/added/launch/openshift-node-name.sh
- jboss/container/wildfly/launch/os/node-name/test/node-name.bats
- jboss/container/wildfly/run/api/module.yaml
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run
- jboss/container/wildfly/run/bash/artifacts/opt/jboss/container/wildfly/run/run-utils.sh
- jboss/container/wildfly/run/bash/test/run.bats
- jboss/container/wildfly/s2i/1.0/bash/module.yaml
Resolves https://issues.redhat.com/browse/JBEAP-25436
Upstream was https://issues.redhat.com/browse/CLOUD-4173
> [0.29.alpha1.x] JBEAP-25436 The jboss.node.name property is incorrectly truncated

- jboss/container/wildfly/galleon/build-feature-pack/module.yaml
Issue: https://issues.redhat.com/browse/EAPPROD-1056
Signed-off-by: Ruben Dario Novelli [rnovelli@redhat.com](mailto:rnovelli@redhat.com)
> [EAPPROD-1056] Add maven-repo and source to jboss.container.wildfly.galleon.build-feature-pack
